apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: lander2k2/sample-webapp
deploy:
  kubectl:
    manifests:
      - k8s*
portForward:
- resourceType: pod
  resourceName: sample-webapp
  namespace: web-app
  port: 8000
  localPort: 9000

